# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: flake8
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-builtin-literals
      - id: mixed-line-ending
      - id: name-tests-test
  - repo: https://github.com/miki725/importanize
    rev: "0.7"
    hooks:
      - id: importanize
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [-l, "79"]
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ""
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.6.0
    hooks:
      - id: blacken-docs
        args: [-l, "79", '-E']
        # additional_dependencies: [black==...]
